type SillyTavermPrompt = {
  chat_completion_source: string;
  openai_model: string;
  claude_model: string;
  windowai_model: string;
  openrouter_model: string;
  openrouter_use_fallback: boolean;
  openrouter_group_models: boolean;
  openrouter_sort_models: 'alphabetically' | 'by-performance';
  openrouter_providers: string[];
  openrouter_allow_fallbacks: boolean;
  openrouter_middleout: 'on' | 'off';
  ai21_model: string;
  mistralai_model: string;
  cohere_model: string;
  perplexity_model: string;
  groq_model: string;
  zerooneai_model: string;
  blockentropy_model: string;
  custom_model: string;
  custom_prompt_post_processing: 'strict' | 'flexible';
  google_model: string;
  temperature: number;
  frequency_penalty: number;
  presence_penalty: number;
  top_p: number;
  top_k: number;
  top_a: number;
  min_p: number;
  repetition_penalty: number;
  openai_max_context: number;
  openai_max_tokens: number;
  wrap_in_quotes: boolean;
  names_behavior: 0 | 1 | 2;
  send_if_empty: string;
  jailbreak_system: boolean;
  impersonation_prompt: string;
  new_chat_prompt: string;
  new_group_chat_prompt: string;
  new_example_chat_prompt: string;
  continue_nudge_prompt: string;
  bias_preset_selected: string;
  max_context_unlocked: boolean;
  wi_format: string;
  scenario_format: string;
  personality_format: string;
  group_nudge_prompt: string;
  stream_openai: boolean;
  prompts: Array<{
    name: string;
    system_prompt: boolean;
    role?: 'system' | 'user' | 'assistant';
    content: string;
    identifier: string;
    injection_position?: number;
    injection_depth?: number;
    forbid_overrides?: boolean;
    marker?: boolean;
    enabled?: boolean;
  }>;
  prompt_order: Array<{
    character_id: number;
    order: Array<{
      identifier: string;
      enabled: boolean;
    }>;
  }>;
  api_url_scale: string;
  show_external_models: boolean;
  assistant_prefill: string;
  assistant_impersonation: string;
  claude_use_sysprompt: boolean;
  use_makersuite_sysprompt: boolean;
  use_alt_scale: boolean;
  squash_system_messages: boolean;
  image_inlining: boolean;
  inline_image_quality: 'low' | 'medium' | 'high';
  bypass_status_check: boolean;
  continue_prefill: boolean;
  continue_postfix: string;
  function_calling: boolean;
  show_thoughts: boolean;
  seed: number;
  n: number;
};
